### ISSUE TITLE
Implement null specification

### ISSUE THREAD

**Issue by jlapacik** [influxdata/flux#1330]
The complete null specification as defined in the SPEC will be implemented when the following issues are closed:

### Done checklist
- [x] Implement null semantics in the interpreter (#1374)
- [x] Implement null semantics in compiler (#1326)
- [x] Implement exists (#1327)
- [x] Refactor object types (#1328)
- [x] Update filter to only return records that evaluate to true (#1329)
- [x] Ensure type checking fails if composite types and regexp types are ever null (#1372)

### Bugs and inconsistencies found
- [ ] Inferring the type of a function call #1366 
- [ ] Constraining the types of binary operands #1356 
- [ ] Accessing a non-existent identifier on an imported package does not error #1373

**Comment by jsternberg** [comment]
This is considered done now. There's still bugs and inconsistencies to resolve, but the underlying feature is done.
