### ISSUE TITLE
Review New Notification Endpoints

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/flux#3541]
Four more notification endpoints have arrived and require review.  This continues to expand our integration footprint and parity with the Kapacitor event handlers.  The BigPanda and ServiceNow implementations were recently introduced into Kapacitor -- and we've validated the approach with end users.  Zenoss is net new.  VictorOps is a port from Kapacitor to Flux.

- [ ] [BigPanda](https://github.com/influxdata/flux/pull/3510)
- [ ] [ServiceNow](https://github.com/influxdata/flux/pull/3276)
- [x] [VictorOps](https://github.com/influxdata/flux/pull/3540)
- [x] [Zenoss](https://github.com/influxdata/flux/pull/3524)
