### ISSUE TITLE
Implement Functions from InfluxQL and TICKscript

### ISSUE THREAD

**Issue by adamperlin** [influxdata/flux#430]
From ifql created by [nathanielc](https://github.com/nathanielc) : influxdata/ifql#85  

This issue tracks progress implementing the various functions that already exist in InfluxQL or TICKscript.

If you want to own adding one of these functions, add your name next to the entry.

### Aggregations
- [x] COUNT
- [x] DISTINCT (see https://github.com/influxdata/influxdb/issues/3880 https://github.com/influxdata/influxdb/issues/3945 ) ( #231)
- [x] INTEGRAL (nc #185 )
- [x] MEAN
- [x] MEDIAN (#234)
- [x] MODE (#1408, custom -- not an aggregation)
- [x] SPREAD (cpg: https://github.com/influxdata/ifql/pull/87)
- [x] STDDEV
- [x] SUM
### Selectors
- [x] BOTTOM (nc #229)
- [x] FIRST
- [x] LAST
- [x] MAX
- [x] MIN
- [x] PERCENTILE - This may need to have both an aggregate implementation and a selector implementation.  (See also: https://github.com/influxdata/influxdb/issues/513) (#234)
- [x] SAMPLE  (Adam)
- [x] TOP (nc #229)
### Transformations
- [x] CEILING  (see https://github.com/influxdata/ifql/issues/266) 
- [x] CUMULATIVE_SUM
- [x] DERIVATIVE (nc #183)
- [x] DIFFERENCE  (nc #186)
- [x] ELAPSED (#1435)
- [x] FLOOR (see https://github.com/influxdata/ifql/issues/266)
- [x] HISTOGRAM
- [x] MOVING_AVERAGE (#1424)
- [x] NON_NEGATIVE_DERIVATIVE - This should be rolled up into the derivative function as an argument.  (nc #183)
- [x] NON_NEGATIVE_DIFFERENCE - This should be rolled up into the difference function as an argument.  (nc #186)

### Functions
- [x] Combine  (create e2e test using join to show equivalency)
- [x] Default  (create e2e test using fill to show equivalency)
- [x] Delete  (create e2e test using drop to show equivalency)
- [x] Derivative (nc #183)   (done above)
- [x] Eval (nc  #179)  (create e2e test using map + with to show equivalency)
- [x] Flatten  (create e2e test using pivot to show equivalency)
- [x] From  (not doing)
- [x] GroupBy
- [x] Join
- [x] NoOp  (covered by yield)
- [x] Query  (not doing)
- [x] Sample
- [x] Shift (adam) https://github.com/influxdata/ifql/pull/181
- [x] StateCount (#230)
- [x] StateDuration (see https://github.com/influxdata/influxdb/issues/7342) (#230)
- [x] Union
- [x] Where
- [x] Window - Only fixed windows by time have been implemented. See https://github.com/influxdata/influxdb/issues/3991 for other ways to window data.

**Comment by wetterfrosch** [comment]
Hi, I am looking for a function for an exponential/power-transformation, like math.pow(base: 5, exponent: 3), is this request here correctly addressed? Within flux v0.12 and Grafana v5.4.3 I am not able to call pow() nor math.pow() nor Math.pow(), already tried adding an "import "math"" in advance, but this results in an internal server error.

**Comment by aanthony1243** [comment]
@wetterfrosch  

As of https://github.com/influxdata/flux/releases/tag/v0.22.0  flux has a math package with includes `pow`.   This should be accessible from both influxdb 2.0 alpha, and the latest version of influxdb 1.7

**Comment by sauren-khosla** [comment]
> Hi, I am looking for a function for an exponential/power-transformation, like math.pow(base: 5, exponent: 3) within an grafana-flux-query. Is this request here correctly addressed? Within flux v0.12 and Grafana v5.4.3 I am not able to call pow() nor math.pow() nor Math.pow(), [I have] already tried adding an "import "math"" in advance, but this results in an internal server error.

@wetterfrosch 
There is now a power operator (`^`) in Flux.

**Comment by wetterfrosch** [comment]
@sauren-khosla Thanks! Cool stuff :)
